### ISSUE TITLE
No such file or directory: RVC-beta/preprocess.log'

### ISSUE THREAD

**Issue by NeMqki** [liujing04/Retrieval-based-Voice-Conversion-WebUI#100]
I downloaded and unzipped RVC-Beta.7z, then installed the latest version from there under releases and put it inside.
However, when I was trying to run it.
I was trying to do step2a of the training and it came up.

runtime\python.exe trainset_preprocess_pipeline_print.py C:\Users\xxxxxx\Documents\VC 48000 16 D:\RVC-beta (1)\RVC-beta/logs/xxxxxxFalse
Traceback (most recent call last):.
  File "D:\RVC-beta (1)\RVC-beta\trainset_preprocess_pipeline_print.py", line 20, in <module
    f = open("%s/preprocess.log" % exp_dir, "a+")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\RVC-beta/preprocess.log'
The following message is displayed.

What should I do?
Past versions were working.
(2023/04/10 version)
![image](https://user-images.githubusercontent.com/24888447/232874203-ea8dd55a-e33b-4679-a4d7-4bb8a5160974.png)

**Comment by NeMqki** [comment]
I may be missing something.
In that case, I apologize.

**Comment by SaltyBarnacles** [comment]
Did you fix it? If so, how?

**Comment by teecil** [comment]
> Did you fix it? If so, how?

I had an error saying that the program could not find the 'preprocess.log' in the path 'D:\\AI/preprocess.log', but the problem is that I never had such a folder on the drive. I created an 'AI' folder on the 'D' drive and put the 'preprocess.log' there from the 'logs' folder, which is in the RVC root folder. It solved error.

**Comment by kalbright3275** [comment]
I had the same problem as well. Once I add an **RVC** folder and append an empty file of the same filename, it finally recognizes it on the next attempt.
