### ISSUE TITLE
Realtime Voice Conversion for RVC

### ISSUE THREAD

**Issue by w-okada** [liujing04/Retrieval-based-Voice-Conversion-WebUI#16]
A really really great job!!!  I'm impressed with how short learning time was and how accurate your results are. I've developed a real-time voice conversion software using RVC, so if you don't mind I'd be really grateful if you could put a link on the Readme.

- repository 
  https://github.com/w-okada/voice-changer
  https://github.com/w-okada/voice-changer/blob/master/README_en.md

- demo
  https://www.youtube.com/watch?v=snCplOwVuMc
  https://twitter.com/DannadoriYellow/status/1643735341067808768?s=20

**Comment by liujing04** [comment]
Done~  I will read your project later

**Comment by w-okada** [comment]
Thanks!!
