### ISSUE TITLE
colab加个tensorboard吧

### ISSUE THREAD

**Issue by KakaruHayate** [liujing04/Retrieval-based-Voice-Conversion-WebUI#19]
%load_ext tensorboard
%tensorboard --logdir /content/Retrieval-based-Voice-Conversion-WebUI/logs

在webUI那格子里，加在注释之前

**Comment by fumiama** [comment]
add in #7

![屏幕快照 2023-04-09 上午12 35 57](https://user-images.githubusercontent.com/41315874/230732691-0941be74-fc6f-4516-9fcc-a2478765c277.png)

**Comment by KakaruHayate** [comment]
> add in #7
> 
> ![屏幕快照 2023-04-09 上午12 35 57](https://user-images.githubusercontent.com/41315874/230732691-0941be74-fc6f-4516-9fcc-a2478765c277.png)

OK，关了
