### ISSUE TITLE
在colab上部署遇到的问题

### ISSUE THREAD

**Issue by ywx2022** [liujing04/Retrieval-based-Voice-Conversion-WebUI#25]
请问在colab上部署用了群里的atri模型
https://i0.hdslb.com/bfs/note/8c93f53e8b51d8345ca619b474d4037133097c3c.png@690w_!web-note.webp
为什么在报错呀
https://i0.hdslb.com/bfs/note/e2e96ad2beaf9a304c177836aa982317ef6303c5.png@690w_!web-note.webp

**Comment by liujing04** [comment]
图片打不开呢

**Comment by fumiama** [comment]
这是你模型没有加载成功。要多刷新几次，直到出现“选择说话人id”的选项，才能进行下一步。
