### ISSUE TITLE
issue running, app.py file missing

### ISSUE THREAD

**Issue by glodcast** [liujing04/Retrieval-based-Voice-Conversion-WebUI#50]
hello it seems that the app.py file was not included in the download and thus i am unable to run the program . Do you think that the file goes under a different name?

**Comment by fumiama** [comment]
Well, you should use the following command to launch the webui.
```bash
python infer-web.py
```

**Comment by glodcast** [comment]
hello, thank you for the awnser. the program now attepmts to run but  the language setting in the infer-web.py is set to swedish insted of one of the existig languges in locale. How would i solve this because i attempted to fin the language code in infer-web.py but was not sucessful.

**Comment by fumiama** [comment]
That's a bug😂We will fix it later.

**Comment by glodcast** [comment]
ok

**Comment by fumiama** [comment]
fixed.
