### ISSUE TITLE
报错显示找不到指定路径，但文件目录内不含空格和特殊字符

### ISSUE THREAD

**Issue by yhj2625312833** [liujing04/Retrieval-based-Voice-Conversion-WebUI#59]
训练时报错
训练材料为语音，目的是训练语音模型
参数设置情况如下：
<img width="783" alt="屏幕截图 2023-04-15 162411" src="https://user-images.githubusercontent.com/53473655/232200510-60010308-69b3-49e1-b147-9fb7dcbbee5a.png">
日志如下：
<img width="887" alt="屏幕截图 2023-04-15 162738" src="https://user-images.githubusercontent.com/53473655/232200770-f98cc25d-d5ca-4f52-a3c0-f77499fe87f5.png">

**Comment by fumiama** [comment]
请说明你使用的版本

**Comment by yhj2625312833** [comment]
使用版本：20230410updated

**Comment by liujing04** [comment]
“很遗憾您这没有能用的显卡能支持您训练”
所以提特征失败了
所以没有3_feature文件夹
