### ISSUE TITLE
训练完成后找不到特征检索库文件：added_IVF677_Flat_nprobe_7.index

### ISSUE THREAD

**Issue by syaofox** [liujing04/Retrieval-based-Voice-Conversion-WebUI#69]
只找到total_fea.npy，找不到added_IVF677_Flat_nprobe_7.index

**Comment by fumiama** [comment]
它可能不叫这个名字，但一定以added_开头。

**Comment by liujing04** [comment]
logs/实验名下如果找不到，点训练索引看看会不会有报错以及之后还有没有这个文件

**Comment by syaofox** [comment]
> logs/实验名下如果找不到，点训练索引看看会不会有报错以及之后还有没有这个文件

确实报错了，我重新训练后找到了
