### ISSUE TITLE
考虑添加文字转语音(TTS)功能吗?

### ISSUE THREAD

**Issue by ZIYONGONLY** [liujing04/Retrieval-based-Voice-Conversion-WebUI#81]
使用自己的语音数据集之后，可以对输入的文本使用训练好模型直接输出该语调下的语音。
例如，我有一篇新闻稿，我希望使用红警HBK08的模型进行新闻的播报。

**Comment by liujing04** [comment]
后面会看看在前面怎么接上TTS，不过将使用的是开源的数据。

**Comment by aiwen324** [comment]
可不可以通过现有的文字转语音工具转成语音然后再做voice conversion? 我也是今天才开始玩这个repo，发现训练好了之后只有转歌声没有转语音的功能ORZ

**Comment by edmund-zhao** [comment]
> 可不可以通过现有的文字转语音工具转成语音然后再做voice conversion? 我也是今天才开始玩这个repo，发现训练好了之后只有转歌声没有转语音的功能ORZ

我也有这个想法。看看能不能用微软的TTS模型输出一些高质量音频文件，然后用这些文件去训练底层模型。

**Comment by edmund-zhao** [comment]
这样就有基于中文训练集的底层模型了，之后只需要训练音色
