### ISSUE TITLE
pip install -r requirements.txt报错

### ISSUE THREAD

**Issue by NijiharaTsubasa** [liujing04/Retrieval-based-Voice-Conversion-WebUI#9]
请问是故意的还是不小心的←_←为什么会有googleads
````

Collecting googleads==3.8.0
  Using cached https://mirrors.aliyun.com/pypi/packages/fa/f8/f84ad483afaa29bfc807ab6e8a06b6712ee494a2aad7db545865655bdf99/googleads-3.8.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in googleads setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

**Comment by NijiharaTsubasa** [comment]
删除googleads之后
````
Collecting ruamel-yaml-conda
  Using cached https://mirrors.aliyun.com/pypi/packages/94/ef/31bfa8456e01ff1  Preparing metadata (setup.py) ... error                                      error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-26tjscuc/ruamel-yaml-conda_ca1bc85899634c92a2eb8c802d6396b0/ruamel_yaml/__init__.py", line 21, in <module>
          from .main import *                               # NOQA                   File "/tmp/pip-install-26tjscuc/ruamel-yaml-conda_ca1bc85899634c92a2eb8c802d6396b0/ruamel_yaml/main.py", line 12, in <module>
          import ruamel.yaml                                                       ModuleNotFoundError: No module named 'ruamel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-26tjscuc/ruamel-yaml-conda_ca1bc85899634c92a2eb8c802d6396b0/setup.py", line 14, in <module>
          import ruamel_yaml  # NOQA                                                 File "/tmp/pip-install-26tjscuc/ruamel-yaml-conda_ca1bc85899634c92a2eb8c802d6396b0/ruamel_yaml/__init__.py", line 23, in <module>
          from ruamel_yaml.main import *                               # NOQA        File "/tmp/pip-install-26tjscuc/ruamel-yaml-conda_ca1bc85899634c92a2eb8c802d6396b0/ruamel_yaml/main.py", line 12, in <module>                               import ruamel.yaml                                                       ModuleNotFoundError: No module named 'ruamel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

**Comment by NijiharaTsubasa** [comment]
手动运行了pip install ruamel.yaml和conda install ruamel.yaml（两个指令都是Google搜的）之后

我搞不定了，救命
````
Collecting ruamel-yaml-conda                                                   Using cached https://mirrors.aliyun.com/pypi/packages/94/ef/31bfa8456e01ff13d8d98bdbc80ab2e592c830e52ccaff62c35d5f890357/ruamel_yaml_conda-0.15.80.tar.gz (202 kB)
  Preparing metadata (setup.py) ... error                                      error: subprocess-exited-with-error                                        
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nsnxrkh6/ruamel-yaml-conda_cfce9d13e9ae4a85b8c11d278dffd58b/setup.py", line 35, in <module>
          ext_modules=cythonize(extensions),                                         File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(                      File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)                                              ValueError: 'ruamel_yaml/ext/_ruamel_yaml.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

**Comment by NijiharaTsubasa** [comment]
总之希望能有个手动配置环境的说明，或者至少把需要的python版本一类的写清楚吧，不是所有用户都是程序员，也不是所有程序员都懂ai（比如我。。。）

**Comment by Gillwindy** [comment]
ruamel yaml在conda里装可以试试 conda install -c conda-forge ruamel_yaml

**Comment by Gillwindy** [comment]
> 手动运行了pip install ruamel.yaml和conda install ruamel.yaml（两个指令都是Google搜的）之后
> 
> 我搞不定了，救命
> 
> ```
> Collecting ruamel-yaml-conda                                                   Using cached https://mirrors.aliyun.com/pypi/packages/94/ef/31bfa8456e01ff13d8d98bdbc80ab2e592c830e52ccaff62c35d5f890357/ruamel_yaml_conda-0.15.80.tar.gz (202 kB)
>   Preparing metadata (setup.py) ... error                                      error: subprocess-exited-with-error                                        
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [12 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-nsnxrkh6/ruamel-yaml-conda_cfce9d13e9ae4a85b8c11d278dffd58b/setup.py", line 35, in <module>
>           ext_modules=cythonize(extensions),                                         File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 970, in cythonize
>           module_list, module_metadata = create_extension_list(                      File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
>           for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
>         File "/usr/local/lib/python3.8/dist-packages/Cython/Build/Dependencies.py", line 114, in nonempty
>           raise ValueError(error_msg)                                              ValueError: 'ruamel_yaml/ext/_ruamel_yaml.pyx' doesn't match any files
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```

ruamel yaml在conda里装可以试试 conda install -c conda-forge ruamel_yaml

**Comment by NijiharaTsubasa** [comment]
我把报错的依赖都先跳过去不装，最后给我报了个找不到torch2.0.0，我彻底不知道我环境什么东西版本有问题了，我租的云服务器（本地没显卡是这样的）
我先用那个colab一键包对付下吧，colab404还随时可能被掐毕竟还是不方便

**Comment by Gillwindy** [comment]
> 我把报错的依赖都先跳过去不装，最后给我报了个找不到torch2.0.0，我彻底不知道我环境什么东西版本有问题了，我租的云服务器（本地没显卡是这样的） 我先用那个colab一键包对付下吧，colab404还随时可能被掐毕竟还是不方便

Windows可以参考diff-svc的部署教程，因为我就是参考这个部署的，装不上的包能删就删了。
https://diff-svc.gitbook.io/the-beginners-guide-to-diff-svc/setting-up/setting-up-the-environment

**Comment by NijiharaTsubasa** [comment]
> > 我把报错的依赖都先跳过去不装，最后给我报了个找不到torch2.0.0，我彻底不知道我环境什么东西版本有问题了，我租的云服务器（本地没显卡是这样的） 我先用那个colab一键包对付下吧，colab404还随时可能被掐毕竟还是不方便
> 
> Windows可以参考diff-svc的部署教程，因为我就是参考这个部署的，装不上的包能删就删了。 https://diff-svc.gitbook.io/the-beginners-guide-to-diff-svc/setting-up/setting-up-the-environment

Linux。。。

**Comment by gak123** [comment]
我的锅，req是在3.8环境下导出的，因此存在一些奇怪的依赖错误
晚点我根据windows版一键包试着在3.9下重新配一遍吧

**Comment by chenxvb** [comment]
> 我把报错的依赖都先跳过去不装，最后给我报了个找不到torch2.0.0，我彻底不知道我环境什么东西版本有问题了，我租的云服务器（本地没显卡是这样的） 我先用那个colab一键包对付下吧，colab404还随时可能被掐毕竟还是不方便

我试了用 pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 来装 torch 2.0，后面能启动，但是不停报错 FileNotFoundError: [Errno 2] No such file or directory: 'weights/[]'，其它的

**Comment by liujing04** [comment]
均已修复。

**Comment by AIhasArrived** [comment]
Hello @NijiharaTsubasa  @Gillwindy  @chenxvb @ricecakey06 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
